Agents/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'agents'

urlpatterns = [
    path('', views.AgentsLogin, name="AgentsLogin"),
    path('agentsregister/',views.AgentsRegister, name="AgentsRegister"),
    path('agentshome/', views.AgentsHome,name="AgentsHomePage"),
    path('agentsorder/', views.Orders, name="AgentsOrders"),
    path('agentsorderdetails/<uuid:uuid_id>/', views.OrderDetails, name="Agentsorderdetails"),
    path('agentsaddproductsinfo/', views.AddProductsInfo, name="Agentsaddproductsinfo"),
    path('agentsaddproductsinfo/<uuid:uuid_id>/', views.AddProducts, name="Agentsaddproducts"),
    path('agentsproducts/', views.Products, name="Agentsproducts"),
    path('agentsproducts/<uuid:uuid_id>/', views.Productsupdate, name="Agentsproductupdate"),
    path('agentsproductsremove/<uuid:uuid_id>/', views.ProductRemove, name="Agentsproductremove"),
    path('shoplocation/<str:str_lat>/<str:str_long>/', views.ShopLoction, name="shoploc"),
    path('addcategory/<uuid:uuid_id>/', views.AddCategory, name="addcategory"),
    path('agentsorderupdate/<uuid:uuid_id>/', views.AgentsOrderUpdate, name="agentsorderupdate"),
    path('selectcategory/', views.SelectCategory, name="selectcategory"),
    



    path('example/', views.example)
]

Dealer/urls.py
from django.urls import path
from . import views

app_name = 'dealers'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.DealerLogin, name="dearlerlogin"),
    path('register/', views.DealerRegister, name="dearlerregister"),
    path('dealerdailyupdate/<str:str_value>/', views.DealerDailyUpdate, name="dealerdailyupdate"),
    path('dealerloc/<str:str_lat>/<str:str_long>/', views.DealerCurrentLocation, name="dealerloc"),
    path('orderdetails/<uuid:uuid_id>/', views.DealerOrderDetails, name="dealerorderdetails"),
    path('orders/', views.DealerOrders, name="dearlerorders"),
    path('directions/<str:long_id>/<str:lat_id>/', views.DealerDirctions, name="directions"),
    path('orderconfirmation/<uuid:uuid_id>/', views.DealerOrderConformation, name="orderconfirmation"),
    path('dealershopsverification/', views.DealerShopsVerification, name="shopsverification"),
    path('shopverify/<uuid:uuid_id>/', views.ShopVerify, name="shopverify")
]

Napsack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('agents/', include('Agents.urls'), name="agents"),
    path('', include('Customer.urls'), name="customer"),
    path('dealer/', include('Dealer.urls'), name="dealer"),
    path('payments/', include('Payments.urls'), name="payments"),
 ]
#
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# from django.conf import settings
# from django.conf.urls.i18n import i18n_patterns
# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import include, path
#
# urlpatterns = i18n_patterns(path('admin/', admin.site.urls), prefix_default_language=False) + \
#     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
#     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Dealer/models.py
from django.db import models
import uuid
from django.utils.timezone import now
# Create your models here.
from phonenumber_field.modelfields import PhoneNumberField
from Agents.models import AgentOrders, AgentLocation
from Customer.models import CustomerOrders


class DealerUsers(models.Model):
    full_name = models.CharField(max_length=30)
    username = models.CharField(max_length=40, unique=True)
    dealer_user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField()
    password = models.CharField(max_length=20)
    phone_number = PhoneNumberField( null=False, blank=False)
    created_on = models.DateTimeField(default=now)
    dealer_verification = models.BooleanField(default=False)
    image = models.ImageField(upload_to='dealer', default='images/shop.jpeg')

    def __str__(self):
        return self.username


class DealertLocation(models.Model):
    username = models.OneToOneField(DealerUsers, on_delete=models.CASCADE, primary_key=True,)
    longitude = models.CharField(max_length=100, default=None)
    latitude = models.CharField(max_length=100, default=None)
    date = models.DateTimeField(default=now)
    dealer_status = models.BooleanField(default=False)
    def __str__(self):
        return f'{self.username.username} Profile'


class DealerOrders(models.Model):
    order_id = models.UUIDField(primary_key=True)
    oder_date = models.DateTimeField(default=now)
    status = models.TextField()
    dealer_status = models.BooleanField(default=False)
    username = models.ForeignKey(DealerUsers, on_delete=models.CASCADE)
    agent_order_id = models.ForeignKey(AgentOrders, on_delete=models.CASCADE)
    customer_order_id = models.ForeignKey(CustomerOrders, on_delete=models.CASCADE)
    delivery_date = models.DateTimeField(default=now)


class DealerShopsVerifications(models.Model):
    username = models.ForeignKey(DealerUsers, on_delete=models.CASCADE)
    date = models.DateTimeField(default=now, )
    verification_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    agent_location = models.ForeignKey(AgentLocation,on_delete=models.CASCADE)
    verify_status = models.BooleanField(default=False)

Dealer/forms.py
from django import forms
from .models import DealerUsers


class DLogin(forms.ModelForm):
    class Meta:
        model = DealerUsers
        fields = ('username', 'password')


class DRegistration(forms.ModelForm):
    class Meta:
        model = DealerUsers
        exclude = ['created_on','dealer_user_id']

    def __init__(self, *args, **kwargs):
        super(DRegistration, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs \
            .update({
            'placeholder': 'Full Name',
            'class': 'login__input'
        })
        self.fields['username'].widget.attrs \
            .update({
            'placeholder': 'Username',
            'class': 'login__input'
        })
        self.fields['email'].widget.attrs \
            .update({
            'placeholder': 'EMail',
            'class': 'login__input'
        })
        self.fields['password'].widget.attrs \
            .update({
            'placeholder': 'Password',
            'class': 'login__input'
        })
        self.fields['phone_number'].widget.attrs \
            .update({
            'placeholder': 'Phone Number',
            'class': 'login__input'
        })

Dealer/views.py
from django.shortcuts import render,HttpResponse, redirect

from Agents.models import AgentOrdersProducts, AgentOrders, AgentsUsers, AgentLocation
from Customer.models import CustomerOrders, CustomerUsers
from . import forms
from Agents.AgentsFunctions import password_check, phone_verify
# Create your views here.
from . import models
from django.contrib import messages
import datetime
from .models import DealerUsers

dealer_currentuser =""

def home(request):
    return render(request, 'layout/dealer_base.html' )



def DealerRegister(request):
    if request.method == "POST":
        form = forms.DRegistration(request.POST)
        pcheck = password_check(request.POST['password'])
        pnum = request.POST['phone_number']
        if pcheck == "correct":
            if phone_verify(pnum):
                if form.is_valid():
                    form.save()
                    check = models.DealerUsers.objects.filter(username=request.POST['username']).values()
                    global dealer_currentuser
                    temp = check[0]
                    dealer_currentuser = temp['dealer_user_id']
                    messages.success(request, f"New account created:")
                    # return render(request, "maps/Shop_location.html")
                    return redirect('dealers:dearlerlogin')
                else:
                    # form = forms.ALogin()
                    messages.error(request, f" UserName already exit...! Try Again  ")
                    # AgentsMessages.my_view(request,f" UserName already exit...! Try Again  ")
                    return render(request, "pages/dealer_register.html", {'form': form})
            else:
                messages.warning(request, f" Invalid Phone Number..! please include country code eg:+91  ")
                return render(request, "pages/dealer_register.html", {'form': form})

        else:
            # form = forms.ALogin()
            messages.warning(request, f" {pcheck} ")
            return render(request, "pages/dealer_register.html", {'form': form})
    else:
        form = forms.DRegistration()
    return render(request, "pages/dealer_register.html", {'form': form})




def DealerLogin(request):
    if request.method == "POST":
        user = request.POST['username']
        pwd = request.POST['password']
        check = models.DealerUsers.objects.filter(username=user, password=pwd).values()
        if check:
            global dealer_currentuser
            temp = check[0]
            dealer_currentuser = temp['dealer_user_id']
            # return redirect('agents:AgentsHomePage')
            return redirect('dealers:home')
        else:
            form = forms.DLogin()
            messages.info(request, f"Invalid UserName and Password...! Try Again ")
            return render(request, "pages/dealer_login.html", {'form': form})
    else:
        form = forms.DRegistration()
    return render(request, "pages/dealer_login.html", {'form': form})


def DealerOrders(request):
    d = models.DealerOrders.objects.filter(username=dealer_currentuser).order_by('oder_date').values()
    data = []
    j = 1
    for i in d:
        temp = i
        temp['sno'] = j
        if i['dealer_status']:
            temp['delivery_status'] = "delivery send"
        else:
            temp['delivery_status'] = "delivery not send"
        data.append(temp)
        j = j + 1
    return render(request, 'pages/dealer_orders.html', {'data': data})


def DealerOrderDetails(request, uuid_id):
    pro_data = AgentOrdersProducts.objects.filter(agentorders_id=uuid_id).values()
    co = CustomerOrders.objects.filter(order_id=uuid_id).values()
    co_one = co[0]
    cu = CustomerUsers.objects.filter(user_id=co_one['customerusername_id']).values()
    cu_one = cu[0]
    ao = AgentOrders.objects.filter(agent_order_id=uuid_id).values()
    ao_one = ao[0]
    du = AgentsUsers.objects.filter(agen_user_id=ao_one['agentsusers_id']).values()
    du_one = du[0]
    aloc = AgentLocation.objects.filter(username=ao_one['agentsusers_id']).values()
    aloc_one = aloc[0]
    user_data = {
        'order_id': uuid_id,
        'cname': cu_one['name'],
        'cphone': cu_one['phone_number'],
        'delivery_date': co_one['delivery_date'],
        'aname': du_one['first_name'] + du_one['last_name'],
        'aphone': du_one['phone_number'],
        'cost': co_one['bill'],
        'no_of_items': len(pro_data),
        'clong': co_one['longitude'],
        'clat': co_one['latitude'],
        'along' :aloc_one['longitude'],
        'alat' : aloc_one['latitude']
    }
    data = {
        'pro_data': pro_data,
        'user_data': user_data
    }
    return render(request, 'pages/dealer_order_details.html', {'data': data})


def DealerDirctions(request, long_id, lat_id):
    loc_data = str(long_id) + "," + str(lat_id)
    return render(request, 'dealer_maps/dealer_directions.html', {'data': loc_data})
def DealerOrderConformation(request, uuid_id):
    do = models.DealerOrders.objects.get(order_id=uuid_id)
    do.dealer_status = True
    current_time = datetime.datetime.now()
    y,m,d,h,mi, = current_time.year, current_time.month,current_time.day,current_time.hour,current_time.minute

    do.status = "Order Deliver on"+ " "  + str(y)+ ":"+str(m)+ ":"+str(d)+ ","+str(h)+ ":"+str(mi)
    ao = AgentOrders.objects.get(agent_order_id=uuid_id)
    ao.delivery_info = "Order Deliver on"+ " " + str(y)+ ":"+str(m)+ ":"+str(d)+ ","+str(h)+ ":"+str(mi)
    uo = CustomerOrders.objects.get(order_id=uuid_id)
    uo.status = "Deliver on "+ " " + str(y)+ ":"+str(m)+ ":"+str(d)+ ","+str(h)+ ":"+str(mi)
    do.save()
    ao.save()
    uo.save()
    return redirect('dealers:dearlerorders')


def DealerShopsVerification(request):
    data = models.DealerShopsVerifications.objects.filter(username=dealer_currentuser).order_by('date').values()
    final_data = []
    for d in data:
        cl = AgentLocation.objects.filter(username=d['agent_location_id']).values()
        cl_one = cl[0]
        cu = AgentsUsers.objects.filter(agen_user_id=cl_one['username_id']).values()
        temp = d
        cu_one = cu[0]
        temp['shopname']= cu_one['agent_shop_name']
        temp['along']= cl_one['longitude']
        temp['alat'] = cl_one['latitude']
        temp['agent_user_id'] = cl_one['username_id']
        final_data.append(temp)
    return render(request, 'pages/verify_shops.html', {'data':final_data})


def ShopVerify(request, uuid_id):
    ds = models.DealerShopsVerifications.objects.get(username_id=dealer_currentuser, agent_location= uuid_id)
    ds_find = models.DealerShopsVerifications.objects.filter(username_id=dealer_currentuser,
                                                             agent_location=uuid_id).values()
    us = AgentsUsers.objects.get(agen_user_id=uuid_id)
    ds_find_one = ds_find[0]
    if ds_find_one['verify_status']:
        ds.verify_status = False
        us.agent_verification = False
    else:
        ds.verify_status = True
        us.agent_verification = True
    ds.save()
    us.save()
    return redirect('dealers:shopsverification')


def DealerDailyUpdate(request,str_value):
    if str_value == "yes":
        return render(request, 'dealer_maps/dealer_current_location.html')
    elif str_value == "no":
        Dl_find = models.DealertLocation.objects.filter(username=dealer_currentuser).values()
        if Dl_find:
            Dl_user = models.DealertLocation.objects.get(username=dealer_currentuser)
            Dl_user.dealer_status = False
            Dl_user.save()
        return HttpResponse("okk done ")
    return render(request, 'pages/daily_update.html')


def DealerCurrentLocation(request,str_lat,str_long):
    Dl_find = models.DealertLocation.objects.filter(username=dealer_currentuser).values()
    print(Dl_find)
    if Dl_find:
        Dl_user = models.DealertLocation.objects.get(username=dealer_currentuser)
        Dl_user.longitude= str_long
        Dl_user.latitude = str_lat
        Dl_user.dealer_status = True
        Dl_user.save()
        return HttpResponse("okk update done")
    else:
        print("sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss")
        print(dealer_currentuser)
        Dl_get = models.DealerUsers.objects.get(dealer_user_id=dealer_currentuser)
        Dl_user = models.DealertLocation(username=Dl_get, longitude=str_long, latitude= str_lat,dealer_status=True)
        Dl_user.save()
        return HttpResponse("okk update done")
    return render(request, 'dealer_maps/dealer_current_location.html')


# insert the data

    # m = models.Members(firstname="adil", lastname="k")
    # m.save()
    # print(m)
    # k or kumar


    # geting all fileds with the list of dist

    # m = models.Members.objects.all().values()
    # print(m)
    # {'id': 1, 'firstname': 'nanda', 'lastname': 'k'}, {'id': 2, 'firstname': 'kumar', 'lastname': 'k'},]


    # to delete the rows

    # member = models.Members.objects.get(id=1)
    # member.delete()
    # print(models.Members.objects.all().values())


    # to update the recodes

    # member = models.Members.objects.get(id=2)
    # member.firstname = "first"
    # member.lastname = "last"
    # member.save()
    # print(models.Members.objects.all().values())


    # to get all list of objects

    # mydata = models.Members.objects.all()
    # print(mydata)
    #
    # list of objects <QuerySet [<Members: last>, <Members: k>]>


    # to get list of all values in the form of dist

    # mydata = models.Members.objects.all().values()


    # to get one column values


    # mydata = models.Members.objects.values_list('firstname').values()
    # print(mydata)
    # list with tuples <QuerySet [('first',), ('adil',)]>


    # to get specific row

    # mydata = models.Members.objects.filter(firstname='adil').values()
    # mydata = models.Members.objects.filter(lastname='Refsnes', id=2).values()

Dealer/templates/pages/daily_update.html
{% extends 'layout/dealer_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/daily_update.css' %}">
{% endblock css %}
{% block itemscontainers %}
<div class="container-add-daily">


    <div class="container-dealer">
        <div class="container-body">
            <aside class="profile-card">

                <header>

                    <!-- here’s the avatar -->
                    <a target="_blank" href="https://twitter.com/xxdionxx">
                        <img src="https://www.dropbox.com/s/9upq789hxnhs361/ava.gif?raw=1">
                    </a>
                    <h1>Dion Pramadhan</h1>
                    <h2>NapSack Delivery Boy</h2>

                </header>

                <!-- bit of a bio; who are you? -->
                <div class="profile-bio">

                    <p>I’m half unicorn and half biscuits. I design <b>ui + ux</b>, i code the <b>frontend</b>, and i love
                        <b>motion design</b>
                    </p>

                </div>
            </aside>
        </div>
    </div>
    <div class="container-upadte">
        <div class="update-info">
            <h2>Are You Coming To job Today...?</h2>
        </div>
        <br>
        <br>
        <div class="update-buttons">
            <a href="{% url 'dealers:dealerdailyupdate' 'yes' %}"><button> Yes I am in </button></a>
            <a href="{% url 'dealers:dealerdailyupdate' 'no' %}"><button> No I am not in </button></a>
        </div>
    </div>
    </div>
{% endblock itemscontainers %}

Dealer/templates/pages/dealer_order_details.html
{% extends 'layout/dealer_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/dealer_order_details.css' %}">
{% endblock css %}
{% block itemscontainers %}
    <br>
    <div style="width: 100%;background:linear-gradient(rgb(168, 247, 247),white)">
        <h2 style="margin-left: 100px">#order id : ddsf-sd54s-664ds</h2>
    </div>
    <div class="orderdetails-container">
        <div class="orderdetails-addressinfo">
            {% for k, i in data.items %}
            {% if forloop.last %}

                        <h2>Shipping Address</h2>
                        <br>
                        <p>{{ i.cname }}, {{ i.cphone }}</p>
                        <h3>Delivery Date & Time : {{ i.delivery_date }} </h3>
                        <br>
                        <a href="{% url 'dealers:directions' i.clong i.clat %}"><button>Get User Location Details</button></a>
                        <br>
                        <br>
                        <h2>Shop Agent Details</h2>
                        <br>
                        <div class="dealer-img-container">
                            <img src="{% static 'images/shop.jpg' %}">
                        </div>
                        <p>{{ i.aname }}, {{ i.aphone }}</p>
                        <br>
                        <a href="{% url 'dealers:directions' i.along i.alat %}"><button>Get User Location Details</button></a>
                        <br>
                        <br>
                        <div class="orderdetails-billandqr">
                            <div class="orderdetails-summary">
                                <h2>Order Summary</h2>
                                    <table>
                                        <tr>
                                            <td>No of items:</td>
                                            <td id="tdsize">{{ i.no_of_items }}</td>
                                        </tr>
                                        <tr>
                                            <td><h3>Grand Total:</h3></td>
                                            <td id="tdsize"><h3>₹{{ i.cost }}</h3></td>
                                        </tr>
                                    </table>
                                    <br>
                                    <p>* Before taking packs please verify no of packs </p>
                                    <br>
                                   <a href="{% url 'dealers:orderconfirmation' i.order_id %}"><button> Send Order </button></a>
                                <br>
                                <br>
                                <br>
                            </div>
                            <div class="orderdetails-qrimg">
                                <img src="{% static 'images/qr.png' %}">
                            </div>
                        </div>

            {% endif %}
            {% endfor %}

        </div>
        <div class="orderdetails-products">
            {% for k, v in data.items %}
                    {% if forloop.first %}
                        {% for j in v %}
            <div class="orderdetails-inner">
                <div style="display: flex; justify-content: space-between;">
                    <p><b>#product-id:{{ j.product_id }}</b></p>
                </div>
                <div class="orderdetails-items">
                    <div class="orderdetails-img">
                        <img src="{% static 'images/item.jpg' %}">
                    </div>
                    <div class="orderdetails-info">
                        <h3>{{ j.name }}</h3>

                        <h3>cat: mobile</h3>
                        <h3>quantity: {{ j.quantity }}</h3>
                        <h3>product cost: {{ j.cost }}</h3>
                    </div>
                </div>
            </div>
             {% endfor %}
            {% endif %}
            {% endfor %}
        </div>

    </div>

{% endblock itemscontainers %}




<!--            <table>-->
<!--                <tr>-->
<!--                    <td>Name</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>Nanda kumar k</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Phone Number:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>6302551161</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Pin code:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>509203</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Locality:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>Nagarkurnool</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Address:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>vattem(vill), bijinapllay(mdl), nagarkurnool(dist),Telangana, 509203 </td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>City/District/Town:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>nagarkurnool</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>State:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td> Telangana</td>-->
<!--                </tr>-->
<!--            </table>-->

Dealer/templates/pages/dealer_orders.html
{% extends 'layout/dealer_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/dealer_orders.css' %}">
{% endblock css %}
{% block itemscontainers %}

<div style="width: 100%;background:linear-gradient(rgb(168, 247, 247),white)">
    <h1 style="text-align: center">OdersPending</h1>
</div>
<div class="orders-container" style="height: 15vh;overflow: hidden; width: 100%;padding: 2% 6% 0 5%;">
    <div class="orders-inner">
        <div class="orders-no">
            <h4>S.N</h4>
        </div>
        <div class="orders-info">
            <h3>#orderid:</h3>
        </div>
        <div class="orders-info">
            <p>ordered on</p>
        </div>
        <div class="orders-info">
            <p>Delivery Date</p>
        </div>
        <div class="orders-info">
            <h4>Status</h4>
        </div>
    </div>
</div>

    <div class="orders-container" style="padding: 0% 5%">
        {% for i in data %}
        <div class="orders-inner">
            <div class="orders-no">
                <h4>{{ i.sno }}</h4>
            </div>
            <div class="orders-info">
                <h3><a href="{% url 'dealers:dealerorderdetails'  i.order_id  %}">{{ i.order_id }} </a></h3>
            </div>
            <div class="orders-info">
                <p>{{ i.oder_date }}</p>
            </div>
            <div class="orders-info">
                <p>{{ i.delivery_date }}</p>
            </div>
            <div class="orders-info">
                <h4>{{ i.delivery_status }}</h4>
            </div>
        </div>
        {% endfor %}
        <br>
        <br>
        <br>
    </div>
{% endblock itemscontainers %}

Dealer/templates/pages/verify_shops.html
{% extends 'layout/dealer_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/verify_shops.css' %}">
{% endblock css %}
{% block itemscontainers %}
    <div class="verifyshop-container">
        {% for i in data %}
              <div class="verifyshop-card">
                      <div class="img-container">
                        <img src="{% static 'images/shop.jpeg' %}">
                      </div>
                      <div class="verifyshop-info">
                            <h2>{{ i.shopname }}</h2>
                              <br>
                            <h3>Longitude:{{ i.along }}</h3>
                            <h3>Latitude: {{ i.alat }}</h3>
                              <br>
                            <div class="verification-container">
                                <a href="{% url 'dealers:directions' i.along i.alat %}"><button style="padding:5%" >View Location</button></a>
                                {% if i.verify_status %}
                              <button style="margin-left: 20px;width: 60px;">Verify</button>
                                {% else %}
                                <a href="{% url 'dealers:shopverify' i.agent_user_id %}"><button style="margin-left: 20px; background:red;width: 60px;">Verify</button></a>
                                {% endif %}
                            </div>
                      </div>
              </div>
        {% endfor %}
    </div>
    
{% endblock itemscontainers %}