Agents/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'agents'

urlpatterns = [
    path('', views.AgentsLogin, name="AgentsLogin"),
    path('agentsregister/',views.AgentsRegister, name="AgentsRegister"),
    path('agentshome/', views.AgentsHome,name="AgentsHomePage"),
    path('agentsorder/', views.Orders, name="AgentsOrders"),
    path('agentsorderdetails/<uuid:uuid_id>/', views.OrderDetails, name="Agentsorderdetails"),
    path('agentsaddproductsinfo/', views.AddProductsInfo, name="Agentsaddproductsinfo"),
    path('agentsaddproductsinfo/<uuid:uuid_id>/', views.AddProducts, name="Agentsaddproducts"),
    path('agentsproducts/', views.Products, name="Agentsproducts"),
    path('agentsproducts/<uuid:uuid_id>/', views.Productsupdate, name="Agentsproductupdate"),
    path('agentsproductsremove/<uuid:uuid_id>/', views.ProductRemove, name="Agentsproductremove"),
    path('shoplocation/<str:str_lat>/<str:str_long>/', views.ShopLoction, name="shoploc"),
    path('addcategory/<uuid:uuid_id>/', views.AddCategory, name="addcategory"),
    path('agentsorderupdate/<uuid:uuid_id>/', views.AgentsOrderUpdate, name="agentsorderupdate"),
    path('selectcategory/', views.SelectCategory, name="selectcategory"),
    



    path('example/', views.example)
]

Napsack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('agents/', include('Agents.urls'), name="agents"),
    path('', include('Customer.urls'), name="customer"),
    path('dealer/', include('Dealer.urls'), name="dealer"),
    path('payments/', include('Payments.urls'), name="payments"),
 ]
#
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# from django.conf import settings
# from django.conf.urls.i18n import i18n_patterns
# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import include, path
#
# urlpatterns = i18n_patterns(path('admin/', admin.site.urls), prefix_default_language=False) + \
#     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
#     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Agents/forms.py
from django import forms
from .models import AgentsUsers


class ALogin(forms.ModelForm):
    class Meta:
        model = AgentsUsers
        exclude = ['created_on', 'agent_shop_id', 'location','agen_user_id']
        # fields = ['first_name']
        # labels = {
        #     'first_name': ('Writer'),
        # }
        # exclude = ('updated', 'created')

    def __init__(self, *args, **kwargs):
        super(ALogin, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs \
            .update({
            'placeholder': 'First Name',
            # 'class': 'input-calss_name'
        })
        self.fields['last_name'].widget.attrs \
            .update({
            'placeholder': 'Last Name',
        })
        self.fields['username'].widget.attrs \
            .update({
            'placeholder': 'Username',
        })
        self.fields['email'].widget.attrs \
            .update({
            'placeholder': 'EMail',
        })
        self.fields['password'].widget.attrs \
            .update({
            'placeholder': 'Password',
        })
        self.fields['phone_number'].widget.attrs \
            .update({
            'placeholder': '+91 Phone Number',
        })
        self.fields['agent_shop_name'].widget.attrs \
            .update({
            'placeholder': 'Shop Name',
        })

Agents/views.py
from turtle import mode
from django.shortcuts import render, HttpResponse, redirect
from Customer import shopsearch

from Customer.cartfunctions import finddealer
from . import forms
from . import models
from NapsackAdmin.models import ProductsCategories, Products as NapProducts, ShopsCategories
from Customer.models import CustomerOrders, CustomerProducts, CustomerUsers
from Dealer.models import DealerOrders, DealerUsers, DealerShopsVerifications
from django.contrib import messages
from . import AgentsMessages
from . import AgentsFunctions

currentuser = ""
agent_long = ""
agent_lat = ""

def AgentsRegister(request):
    if request.method == "POST":
        form = forms.ALogin(request.POST)
        print(form.errors)
        pcheck = AgentsFunctions.password_check(request.POST['password'])
        pnum = request.POST['phone_number']
        if pcheck == "correct":
            if AgentsFunctions.phone_verify(pnum):
                print("checjjjjjjjjjjjj")
                if form.is_valid():
                    form.save()
                    check = models.AgentsUsers.objects.filter(username=request.POST['username']).values()
                    global currentuser
                    temp = check[0]
                    currentuser = temp['agen_user_id']
                    messages.success(request, f"New account created:")

                    return render(request, "maps/Shop_location.html")
                else:
                    # form = forms.ALogin()
                    messages.error(request, f" UserName already exit...! Try Again  ")
                    # AgentsMessages.my_view(request,f" UserName already exit...! Try Again  ")
                    return render(request, "pages/agentsregister.html", {'form': form})
            else:
                messages.warning(request, f" Invalid Phone Number..! please include country code eg:+91  ")
                return render(request, "pages/agentsregister.html", {'form': form})

        else:
            # form = forms.ALogin()
            messages.warning(request, f" {pcheck} ")
            return render(request, "pages/agentsregister.html", {'form': form})
    else:
        form = forms.ALogin()
    return render(request, "pages/agentsregister.html", {'form': form})


def ShopLoction(request,str_lat,str_long):
    print(currentuser)
    us = models.AgentsUsers.objects.get(agen_user_id=currentuser)
    s = models.AgentLocation(username=us,longitude=str_long,latitude=str_lat)
    s.save()
    global agent_long, agent_lat
    agent_long = str_long
    agent_lat = str_lat
    return HttpResponse("Shop Location Added")
    # return redirect('agents:selectcategory')
    # data = ShopsCategories.objects.all().values()
    # print(type(data))
    # print(data)
    # return render(request, 'pages/selectcategory.html', {'data': data})


def AgentsLogin(request):
    if request.method == "POST":
        user = request.POST['username']
        pwd = request.POST['password']
        check = models.AgentsUsers.objects.filter(username=user, password=pwd).values()
        if check:
            check_one = check[0]
            if check_one['agent_verification']:
                global currentuser
                temp = check[0]
                currentuser = temp['agen_user_id']
                print(currentuser)
                return redirect('agents:AgentsHomePage')
            else:
                return HttpResponse("shop not verified ")

        else:
            form = forms.ALogin()
            messages.info(request, f"Invalid UserName and Password...! Try Again ")
            return render(request, "pages/agentslogin.html", {'form': form})
    else:
        form = forms.ALogin()
    return render(request, "pages/agentslogin.html", {'form': form})


def SelectCategory(request):
    data = ShopsCategories.objects.all().values()
    print(type(data))
    print(data)
    return render(request, 'pages/selectcategory.html',{'data': data})


def AddCategory(request, uuid_id):
    print("yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy")
    print(uuid_id)
    us = models.AgentsUsers.objects.get(agen_user_id=currentuser)
    ct = ShopsCategories.objects.get(Shops_id=uuid_id)
    s = models.AgentShopCategorie(username=us,agent_shop_categorie=ct)
    s.save()
    dlr = finddealer(agent_lat, agent_long)
    d = dlr[0]
    dlr_one = d['username_id']
    print("ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss")
    print(dlr_one)
    ag_loc = models.AgentLocation.objects.get(username=currentuser)
    dlr_get = DealerUsers.objects.get(dealer_user_id=dlr_one)
    dealer = DealerShopsVerifications(username=dlr_get, agent_location=ag_loc)
    dealer.save()
    return redirect('agents:AgentsLogin')


def AgentsHome(request):
    return render(request, "layout/base.html")


def Orders(request):
    d = models.AgentOrders.objects.filter(agentsusers=currentuser).order_by('order_date').values()
    data = []
    j = 1
    for i in d:
        temp = i
        temp['sno'] = j
        if i['delivery_status']:
            temp['delivery_status'] = "delivery send"
        else:
            temp['delivery_status'] = "delivery not send"
        data.append(temp)
        j = j+1
    return render(request, "pages/orders.html", {'data': data})


def OrderDetails(request, uuid_id):
    pro_data =  models.AgentOrdersProducts.objects.filter(agentorders_id=uuid_id).values()
    co = CustomerOrders.objects.filter(order_id= uuid_id).values()
    co_one = co[0]
    cu = CustomerUsers.objects.filter(user_id=co_one['customerusername_id']).values()
    cu_one = cu[0]
    Do = DealerOrders.objects.filter(order_id=uuid_id).values()
    Do_one = Do[0]
    du = DealerUsers.objects.filter(dealer_user_id=Do_one['username_id']).values()
    du_one =  du[0]
    temp = []
    for i in pro_data:
        img_url = models.AgentOrdersProducts.objects.get(product_id=i['product_id'])
        t = i
        t['img'] = img_url
        temp.append(t)
    qr_data = "orderid:%40"+str(uuid_id)+"%0Aname:%40"+cu_one['name']+"%0Aphone%20number:%40"+cu_one['phone_number']+"%0Ano%20of%20products:%40"+str(len(pro_data))+"%0Acost:%40"+str(co_one['bill'])
    qr_url = f'https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl={qr_data}&choe=UTF-8'
    user_data = {
        'order_id' :uuid_id,
        'cname': cu_one['name'],
        'cphone':cu_one['phone_number'],
        'delivery_date': co_one['delivery_date'],
        'dname': du_one['full_name'],
        'dphone': du_one['phone_number'],
        'cost': co_one['bill'],
        'no_of_items': len(pro_data),
        'qr_url': qr_url,
    }
    data = {
        'pro_data': temp,
        'user_data': user_data
    }
    return render(request, "pages/orderdetails.html", {'data': data})


def ProductsCheck(uuid_id):
    all_products = NapProducts.objects.filter(categories_id=uuid_id).values()
    products = models.AgentProducts.objects.filter(agentsusers=currentuser).values()
    # print(all_products)
    # print(products)
    productdata = []

    for apr in all_products:
        products = models.AgentProducts.objects.filter(agentsusers=currentuser,product_id_id=apr['product_id'] ).values()
        if products:
            continue
        else:
            img_url = NapProducts.objects.get(product_id=apr['product_id'])
            temp = apr
            temp['img'] = img_url
            productdata.append(temp)

    agent_categories = models.AgentShopCategorie.objects.filter(username=currentuser).values()
    tac = agent_categories[0]
    tac_id = tac['agent_shop_categorie_id']
    all_categories = models.ProductsCategories.objects.filter(shop_id=tac_id).order_by(
        'name').values()
    print("llllllllllllllllllllllllllllllll")
    print(len(productdata))

    data = {
        'categories': all_categories,
        'products': productdata,
    }
    return data


def AddProductsInfo(request):
    agent_categories = models.AgentShopCategorie.objects.filter(username=currentuser).values()
    print(agent_categories)
    tac = agent_categories[0]
    print(tac)
    tac_id = tac['agent_shop_categorie_id']
    print(tac_id)
    all_categories = models.ProductsCategories.objects.filter(shop_id=tac_id).order_by(
        'name').values()
    print(all_categories)
    t1c = all_categories[0]
    t1cid = t1c['categories_id']
    data = ProductsCheck(t1cid)
    print("rgggggggggggggggggggggggggggggghdzhf;siuhnskjb;Adjjjjjjjjjjjjjjjjjjjjjjjjjskd>djdsfnsjnskjnskgvnrsknfwsf")
    print(type(data))
    for i in data:
        print(i)
    print(data)
    return render(request, "pages/addproducts.html", {'data': data})



def AddProducts(request, uuid_id):
    if request.method == "POST":
        Icost = request.POST['cost']
        Ioffer = request.POST['offer']
        Inoofitemspresent = request.POST['noofitemspresent']
        us = models.AgentsUsers.objects.get(agen_user_id=currentuser)
        pt = NapProducts.objects.get(product_id=uuid_id)
        find_cat = NapProducts.objects.filter(product_id=uuid_id).values()
        find_cat_one = find_cat[0]
        f_get = ProductsCategories.objects.get(categories_id=find_cat_one['categories_id_id'])
        f_cat_name = ProductsCategories.objects.filter(categories_id=find_cat_one['categories_id_id']).values()
        f_cat_name_one = f_cat_name[0]
        m = models.AgentProducts(agentsusers=us,product_id=pt, cost=Icost, offer=Ioffer,
                             quantity_present=Inoofitemspresent, Categories_name=f_cat_name_one['name'],categories=f_get)
        m.save()

        return redirect('agents:Agentsaddproductsinfo')
    else:
        data = ProductsCheck(uuid_id)
        return render(request, "pages/addproducts.html", {'data': data})



def UpdateProductCheck():
    products_agent = models.AgentProducts.objects.filter(agentsusers=currentuser).values()
    print(type(products_agent))
    data = []
    for pro in products_agent:

Agents/templates/pages/addproducts.html
{% extends 'layout/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/addproducts.css' %}">
{% endblock css %}
{% block itemscontainers %}
    <div style="width: 100%;background:linear-gradient(rgb(168, 247, 247),white)">
        <h1 style="text-align: center">Add products to your shop</h1>
    </div>
    <div class="addproducts-container">
        <div class="addproducts-left">
            <br>
            <div style="width: 100%;">
                <h2 style="text-align: center">Categories</h2>
                <hr>
            </div>
            <br>
            <ul>
                {% for k, v in data.items %}
                    {% if forloop.first %}
                        {% for j in v %}
                            <li><a href="{% url 'agents:Agentsaddproducts'  j.categories_id  %}">{{ j.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="addproducts-right">
            <!-- <div style="width: 100%;background:linear-gradient(rgb(168, 247, 247),white)">
                <h2 style="text-align: left">Catgory name</h2>
            </div> -->
            <br>
            {% for v,k in data.items %}
                {% if forloop.last %}
                    {% if k %}
                    {% for j in k %}
                        <div class="addproducts-products">
                            <div class="addproducts-img">
                                <img src="{{ j.img.image.url }}">
                            </div>
                            <div class="addproducts-info">
                                <h4>{{ j.name }}</h4>
                                <form action="{% url 'agents:Agentsaddproducts' j.product_id %}" method="post">
                                    {% csrf_token %}
                                    <table>
                                        <tr>
                                            <td>Cost</td>
                                            <td id="tdsize"> <input type="text" name="cost" required></td>
                                        </tr>
                                        <tr>
                                            <td>Offer %</td>
                                            <td id="tdsize">  <input type="text" name="offer" ></td>
                                        </tr>
                                        <tr>
                                            <td>No of items present</td>
                                            <td><input type="text" name="noofitemspresent" required></td>
                                        </tr>
                                    </table>

                                    <input type="submit" value="Add"  style="float: right" >
                                </form>
                                <br> 
                            </div>
                        </div>
                    {% endfor %}
                    {% else %}
                        <h2 style="text-align: center;margin-top: 20%;color: rgb(245, 174, 40);">No products to add in this category</h2>
                    {% endif %}
                {% endif %}
            {% endfor %}

        </div>
    </div>
    <script>
        function onadd(ids){
            document.getElementById(ids).style.background = "blue";
        }
    </script>
{% endblock itemscontainers %}

Agents/templates/pages/agentslogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" type="text/css"  href="{% static 'pages/agentslogin.css' %}" />
    <title>Sign in & Sign up Form</title>
  </head>
  <body>
    <div class="container">
      <div class="forms-container">

        <div class="signin-signup">

          <form  class="sign-in-form" method="post">
            {% csrf_token %}
            <h2 class="title">Sign in</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Username" name="username"/>
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" name="password"/>
            </div>
            {% if messages %}
              {% for message in messages %}
                 {% if message.tags == 'info'%}
                  <div style="height: 40px;width: 320px;color: darkred">
                    <strong>{{message}}</strong>
                  </div>
                 {% endif %}
              {% endfor %}
              {% endif %}
            <input type="submit" value="Login" class="btn solid" />
          </form>


          <form action="{% url 'agents:AgentsRegister' %}" class="sign-up-form" method="post">
            {% csrf_token %}
            <h2 class="title">Sign up</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              {{ form.first_name }}
<!--              <input type="text" placeholder="Username" />-->
            </div>
            <div class="input-field">
              <i class="fas fa-user"></i>
              {{ form.last_name }}
            </div>
            <div class="input-field">
              <i class="fas fa-user"></i>
              {{ form.username }}
            </div>
            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'error'%}
            <div style="height: 40px;width: 320px;color: darkred">
              <strong>{{message}}</strong>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              {{ form.email }}
<!--              <input type="email" placeholder="Email" />-->
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              {{ form.password }}
<!--              <input type="password" placeholder="Password" />-->
            </div>
            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'warning'%}
            <div style="height: 40px;width: 320px;color: darkred">
              <strong>{{message}}</strong>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
             <div class="input-field">
              <i class="fas fa-user"></i>
              {{ form.phone_number }}
            </div>
            <div class="input-field">
              <i class="fas fa-user"></i>
              {{ form.agent_shop_name }}
            </div>
            <input type="submit" class="btn" value="Sign up" />
          </form>

        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <img src="{% static 'images/logo-white.png' %}"  alt="">
             <br><br>
            <h3>New here ?</h3>
            <p>
              lets get you started ? <br>
              create your free account today to join and utilise our services!
            </p>
            <button class="btn transparent" id="sign-up-btn">
              Sign up
            </button>
          </div>
          <img src="{% static 'images/pages/logo-1.png' %}" class="image" alt="" style="height: 470px">
        </div>
        <div class="panel right-panel">
          <div class="content">
            <img src="{% static 'images/logo-white.png' %}"  alt="">
            <br><br>
            <h3>One of us ?</h3>
            <p>
              log on to your account to let us know where we've been left !
            </p>
            <button class="btn transparent" id="sign-in-btn">
              Sign in
            </button>
          </div>
          <img src="{% static 'images/pages/logo-2.png' %}" class="image" alt="" style="height: 470px">
        </div>
      </div>
    </div>

    <script>
      const sign_in_btn = document.querySelector("#sign-in-btn");
const sign_up_btn = document.querySelector("#sign-up-btn");
const container = document.querySelector(".container");

sign_up_btn.addEventListener("click", () => {
  container.classList.add("sign-up-mode");
});

sign_in_btn.addEventListener("click", () => {
  container.classList.remove("sign-up-mode");
});

    </script>

  </body>
</html>

Agents/templates/pages/orderdetails.html
{% extends 'layout/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/orderdetails.css' %}">
{% endblock css %}
{% block itemscontainers %}
    <br>
    <div style="width: 100%;">
        {% for k, i in data.items %}
            {% if forloop.last %}
        <h2 style="margin-left: 100px">#order id : {{ i.order_id }}</h2>
        {% endif %}
            {% endfor %}
    </div>
    <div class="orderdetails-container">
        <div class="orderdetails-addressinfo">
            {% for k, i in data.items %}
            {% if forloop.last %}

                        <h2>Shipping Address</h2>
                        <br>
                        <p>{{ i.cname }}, {{ i.cphone }}</p>
                        <h3>Delivery Date & Time : {{ i.delivery_date }} </h3>
                        <br>
                        <h2>Delivery Dealer Details</h2>
                        <br>
                        <div class="dealer-img-container">
                            <img src="{% static 'images/shop.jpg' %}">
                        </div>
                        <p>{{ i.dname }}, {{ i.dphone }}</p>

                        <br>
                        <div class="orderdetails-billandqr">
                            <div class="orderdetails-summary">
                                <h2>Order Summary</h2>
                                    <table>
                                        <tr>
                                            <td>No of items:</td>
                                            <td id="tdsize">{{ i.no_of_items }}</td>
                                        </tr>
                                        <tr>
                                            <td><h3>Grand Total:</h3></td>
                                            <td id="tdsize"><h3>₹{{ i.cost }}</h3></td>
                                        </tr>
                                    </table>
                                    <br>
                                    <p>* Before send Pack All Products in Bag </p>
                                    <br>
                                    <a href="{% url 'agents:agentsorderupdate' i.order_id %}"><button> Send Order </button></a>
                            </div>
                            <div class="orderdetails-qrimg">
                                <img src="{{ i.qr_url }}">
                            </div>
                        </div>

            {% endif %}
            {% endfor %}

        </div>
        <div class="orderdetails-products">
            {% for k, v in data.items %}
                    {% if forloop.first %}
                        {% for j in v %}
            <div class="orderdetails-inner">
                <div style="display: flex; justify-content: space-between;">
                    <p><b>#product-id:{{ j.product_id }}</b></p>
                </div>
                <div class="orderdetails-items">
                    <div class="orderdetails-img">
                        <img src="{{ j.img.image.url }}">
                    </div>
                    <div class="orderdetails-info">
                        <b><p>{{ j.name }}</p></b>
                        <b><p>Categorie: {{ j.Categorie }}</p></b>
                        <b><p>quantity: {{ j.quantity }}</p></b>
                        <b><p>product cost: {{ j.cost }}</p></b>
                    </div>
                </div>
            </div>
             {% endfor %}
            {% endif %}
            {% endfor %}
        </div>

    </div>

{% endblock itemscontainers %}




<!--            <table>-->
<!--                <tr>-->
<!--                    <td>Name</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>Nanda kumar k</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Phone Number:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>6302551161</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Pin code:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>509203</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Locality:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>Nagarkurnool</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>Address:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>vattem(vill), bijinapllay(mdl), nagarkurnool(dist),Telangana, 509203 </td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>City/District/Town:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td>nagarkurnool</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>State:</td>-->
<!--                    <td id="col">:</td>-->
<!--                    <td> Telangana</td>-->
<!--                </tr>-->
<!--            </table>-->

Agents/templates/pages/orders.html
{% extends 'layout/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/orders.css' %}">
{% endblock css %}
{% block itemscontainers %}

<div style="width: 100%;background:linear-gradient(rgb(168, 247, 247),white)">
    <h1 style="text-align: center">Orders</h1>
</div>
<div class="orders-container" style="height: 15vh;overflow: hidden; width: 100%;padding: 2% 6% 0 5%;">
    <div class="orders-inner">
        <div class="orders-no">
            <h4>S.N</h4>
        </div>
        <div class="orders-info">
            <h3>#orderid:</h3>
        </div>
        <div class="orders-info">
            <p>ordered on</p>
        </div>
        <div class="orders-info">
            <p>Delivery Date</p>
        </div>
        <div class="orders-info">
            <h4>Status</h4>
        </div>
    </div>
</div>

    <div class="orders-container" style="padding: 0% 5%">
        {% for i in data %}
        <div class="orders-inner">
            <div class="orders-no">
                <h4>{{ i.sno }}</h4>
            </div>
            <div class="orders-info">
                <h3><a href="{% url 'agents:Agentsorderdetails'  i.agent_order_id  %}">{{ i.agent_order_id }} </a></h3>
            </div>
            <div class="orders-info">
                <p>{{ i.order_date }}</p>
            </div>
            <div class="orders-info">
                <p>{{ i.delivery_date }}</p>
            </div>
            <div class="orders-info">
                <h4>{{ i.delivery_status }}</h4>
            </div>
        </div>
        {% endfor %}
        <br>
        <br>
        <br>
    </div>
{% endblock itemscontainers %}

Agents/templates/pages/products.html
{% extends 'layout/base.html' %}
{% load static %}
{% block css %}
{% load bootstrap_icons %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/products.css' %}">
{% endblock css %}
{% block itemscontainers %}
    <!-- <div style="width: 100%;background:linear-gradient(rgb(168, 247, 247),white)">
        <h1 style="text-align: center">Products</h1>
    </div> -->
    <br>
    <div class="product-search-conatiner">
        <form action="{% url 'agents:Agentsproducts' %}" method="post">
            {% csrf_token %}
            <input type="text" name="search" placeholder="Search Products" >
            <button type="submit" style="border: none;">{% bs_icon 'search' size='1.5em' %}</button>
        </form>
    </div>
    <br>
    <hr>
    <div class="products-container" id="products">
        {% for info in productsdata %}
                    <div class="products-inner">
                        <div class="products-img">
                            <img src="{{ info.img.image.url }}">
                            <p>{{ info.image_id }}</p>
                        </div>
                        <div class="products-info">
                            <h4>{{ info.name }}</h4>
                            <br>
                            <p>category: {{ info.categories_id }}</p>
                            <p>Cost: {{ info.cost }}</p>
                            <p>Offer %: {{ info.offer }}</p>
                            <p>No of items Present: {{ info.quantity_present }}</p>
                            <button style="float: right;" onclick="onsubmitevent('open')" >
                                <a href= "{% url 'agents:Agentsproductupdate' info.agent_product_id %}"> Update</a></button>
                            <button style="float: right;margin-right: 150px">
                                <a href= "{% url 'agents:Agentsproductremove' info.agent_product_id %}"> Remove</a></button>
                        </div>
                    </div>
        {% endfor %}

{% endblock itemscontainers %}