Agents/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'agents'

urlpatterns = [
    path('', views.AgentsLogin, name="AgentsLogin"),
    path('agentsregister/',views.AgentsRegister, name="AgentsRegister"),
    path('agentshome/', views.AgentsHome,name="AgentsHomePage"),
    path('agentsorder/', views.Orders, name="AgentsOrders"),
    path('agentsorderdetails/<uuid:uuid_id>/', views.OrderDetails, name="Agentsorderdetails"),
    path('agentsaddproductsinfo/', views.AddProductsInfo, name="Agentsaddproductsinfo"),
    path('agentsaddproductsinfo/<uuid:uuid_id>/', views.AddProducts, name="Agentsaddproducts"),
    path('agentsproducts/', views.Products, name="Agentsproducts"),
    path('agentsproducts/<uuid:uuid_id>/', views.Productsupdate, name="Agentsproductupdate"),
    path('agentsproductsremove/<uuid:uuid_id>/', views.ProductRemove, name="Agentsproductremove"),
    path('shoplocation/<str:str_lat>/<str:str_long>/', views.ShopLoction, name="shoploc"),
    path('addcategory/<uuid:uuid_id>/', views.AddCategory, name="addcategory"),
    path('agentsorderupdate/<uuid:uuid_id>/', views.AgentsOrderUpdate, name="agentsorderupdate"),
    path('selectcategory/', views.SelectCategory, name="selectcategory"),
    



    path('example/', views.example)
]

Customer/urls.py
from django.urls import path
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'customers'

urlpatterns = [
    path('home/<str:home_lat>/<str:home_long>/', views.Home, name="home"),
    path('', views.FirstHome, name="firstgome"),
    path('addtocart/<uuid:uuid_id>/', views.AddtoCart, name="addtocart"),
    path('removecart/<uuid:uuid_id>/', views.RemoveCart, name="removecart"),
    path('cartbill/<str:quantity>/', views.CartBill, name="cartbill"),
    path('paynow/', views.PayNow, name="paynow"),
    path('login/', views.Logins, name="login"),
    path('register/', views.Registers, name="register"),
    path('orders/', views.Orders, name="Orders"),
    path('cart/', views.Cart, name = "cart"),
    path('Phoneverify/', views.Phoneverify, name="Phoneverify"),
    path('OtpVerify/', views.OtpVerify, name="Otp"),
    path('customerproducts/<uuid:uuid_id>/', views.Products, name ="products"),
    path('specificcat/<uuid:uuid_id>/', views.SpecificCategory, name="specificcat"),
    path('customerproduct/<uuid:uuid_id>/', views.Product, name ="product"),
    path('currentloc/<str:str_lat>/<str:str_long>/', views.CurrentLoc, name="curloc"),
    path('mobileverify/<str:str_info>/', views.MobileVerify, name="mobileverify"),
    path('specificshop/<uuid:uuid_id>/', views.SpecificShop, name="specificshop"),
    path('shops/', views.Shops, name="shop"),
    path('deliveryoption/', views.DeliveryOption, name="deliveryoption"),
    re_path(r'^payment/(?P<p>.*)$', views.PaymentVerifyRequest),
    path('cashondeliver/', views.CashOnDeliveryRequest, name="cashonedelivery"),
    path('logout/', views.LogOut, name="logout"),
    path('shopsearch/', views.ShopSearch, name="shopsearch"),
    path('productsearch/', views.ProductSearch, name="productsearch"),
    path('shopnotfiund/', views.ShopNotFound, name="shopnotfound"),
    path('customerprofile/', views.CustomerProfile, name="customerprofile"),
    path('customerimage/', views.UpdateProfileImage, name="customerimage"),
    path('customerforgotpassword/', views.ForgotPassword, name="forgotpassword"),
    path('customerupdatepassword/', views.UpdateForgotPassword, name="updatepassword"),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

Dealer/urls.py
from django.urls import path
from . import views

app_name = 'dealers'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.DealerLogin, name="dearlerlogin"),
    path('register/', views.DealerRegister, name="dearlerregister"),
    path('dealerdailyupdate/<str:str_value>/', views.DealerDailyUpdate, name="dealerdailyupdate"),
    path('dealerloc/<str:str_lat>/<str:str_long>/', views.DealerCurrentLocation, name="dealerloc"),
    path('orderdetails/<uuid:uuid_id>/', views.DealerOrderDetails, name="dealerorderdetails"),
    path('orders/', views.DealerOrders, name="dearlerorders"),
    path('directions/<str:long_id>/<str:lat_id>/', views.DealerDirctions, name="directions"),
    path('orderconfirmation/<uuid:uuid_id>/', views.DealerOrderConformation, name="orderconfirmation"),
    path('dealershopsverification/', views.DealerShopsVerification, name="shopsverification"),
    path('shopverify/<uuid:uuid_id>/', views.ShopVerify, name="shopverify")
]

Napsack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('agents/', include('Agents.urls'), name="agents"),
    path('', include('Customer.urls'), name="customer"),
    path('dealer/', include('Dealer.urls'), name="dealer"),
    path('payments/', include('Payments.urls'), name="payments"),
 ]
#
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# from django.conf import settings
# from django.conf.urls.i18n import i18n_patterns
# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import include, path
#
# urlpatterns = i18n_patterns(path('admin/', admin.site.urls), prefix_default_language=False) + \
#     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
#     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Customer/forms.py
from django import forms
from .models import CustomerImages, CustomerUsers

class CLogin(forms.ModelForm):
    class Meta:
        model = CustomerUsers
        fields = ('username', 'password')


class CRegistration(forms.ModelForm):
    class Meta:
        model = CustomerUsers
        exclude = ['created_on']

    def __init__(self, *args, **kwargs):
        super(CRegistration, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs \
            .update({
            'placeholder': 'Full Name',
            # 'class': 'input-calss_name'
        })
        self.fields['username'].widget.attrs \
            .update({
            'placeholder': 'Username',
        })
        self.fields['email'].widget.attrs \
            .update({
            'placeholder': 'EMail',
        })
        self.fields['password'].widget.attrs \
            .update({
            'placeholder': 'Password',
        })
        self.fields['phone_number'].widget.attrs \
            .update({
            'placeholder': 'Phone Number',
        })


class CustomerImagesForm(forms.ModelForm):
    class Meta:
        model = CustomerImages
        fields = ['image']

Customer/views.py
import email
from statistics import mode
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse
from . import shopsearch

from Customer.shopsearch import search
from . import forms
from Agents.AgentsFunctions import phone_verify, password_check
from . import models
from django.contrib import messages
import random
import requests
from django.shortcuts import redirect, reverse
from  . import locationfunctions
from Agents.models import AgentShopCategorie, AgentProducts, AgentsUsers
from NapsackAdmin.models import ShopsCategories,Products as Napproducts,ProductsCategories
from . import payments
from . import cartfunctions
import random
currentuser = ""
mnumber = ""
lat = "16.439135"
long = "80.624908"
# lat = ""
# long = ""
shopid = ""
cart_bill_data = []
sp = ""
phone_verification = True

def Phoneverify(request):
    if request.method == 'POST':
        po = request.POST['phone']
        otp = random.randint(1000, 9999)
        x = requests.request("GET", f'https://2factor.in/API/V1/df1606dc-a515-11ec-a4c2-0200cd936042/SMS/{po}/{otp}/NapSack')
        s = x.json()
        # global temp
        # temp = otp
        if s['Status'] == "Success":
            return redirect(reverse('Otp'))
        else:
            return HttpResponse("<h1>try again</h1>")

    return render(request, "forms/PhoneVerify.html")


def OtpVerify(request):
    # if request.method == 'POST':
    #     otp = request.POST['otp']
    #     if otp == str(temp):
    #         return redirect(reverse('Register'))
    #     else:
    #         return HttpResponse("<h1>wrong</h1>")
    return render(request, "forms/otpverify.html")

votp = 0
def MobileVerify(request, str_info):
    global votp
    if str_info == "new":
        cuser = models.CustomerUsers.objects.filter(user_id=currentuser).values()
    else:
        cuser = models.CustomerUsers.objects.filter(username=str_info).values()
    cuser_one = cuser[0]
    phone_number = cuser_one['phone_number']
    data = {
        'phone': phone_number,
        'info': str_info
    }
    if request.method == 'POST':
        v1 = request.POST['v1']
        v2 = request.POST['v2']
        v3 = request.POST['v3']
        v4 = request.POST['v4']
        v5 = request.POST['v5']
        otp = v1+v2+v3+v4+v5
        if otp == str(votp):
            if str_info == "new":
                models.CustomerUsers.objects.filter(user_id=currentuser).update(phone_verify=True)
                return redirect('customers:login')
            else:
                return redirect('customers:updatepassword')
        else:
            messages.error(request, f" Invalid OTP...! Try Again ")
            return render(request, 'pages/MobileVerify.html', {'data':data})
    else:
        # otp = random.randint(10000, 99999)
        otp = 11111
        # x = requests.request("GET",f'https://2factor.in/API/V1/df1606dc-a515-11ec-a4c2-0200cd936042/SMS/{phone_number}/{otp}/NapSack')
        # s = x.json()
        votp = otp
        # if s['Status'] == "Success":
        return render(request, 'pages/MobileVerify.html', {'data':data})
        # else:
        #     return HttpResponse("<h1>try again</h1>")



def Registers(request):
    if request.method == "POST":
        form = forms.CRegistration(request.POST, request.FILES)
        print(form.errors)
        pcheck = password_check(request.POST['password'])
        pnum = request.POST['phone_number']
        if pcheck == "correct":
            if phone_verify(pnum):
                print("checjjjjjjjjjjjj")
                if form.is_valid():
                    form.save()
                    cusername = form.cleaned_data['username']
                    c_user = models.CustomerUsers.objects.filter(username=cusername).values()
                    c_user_one = c_user[0]
                    customer_image_save = models.CustomerImages(user_id = c_user_one['user_id'])
                    customer_image_save.save()
                    global currentuser
                    currentuser = c_user_one['user_id']
                    messages.success(request, f"New account created:")
                    return redirect('customers:mobileverify', "new")
                    # return redirect('customers:login')
                else:
                    # form = forms.ALogin()
                    messages.error(request, f" UserName already exit...! Try Again  ")
                    # AgentsMessages.my_view(request,f" UserName already exit...! Try Again  ")
                    return render(request, "pages/customer_register.html", {'form': form})
            else:
                messages.warning(request, f" Invalid Phone Number..! please include country code eg:+91  ")
                return render(request, "pages/customer_register.html", {'form': form})

        else:
            # form = forms.ALogin()
            messages.info(request, f" {pcheck} ")
            return render(request, "pages/customer_register.html", {'form': form})
    else:
        form = forms.CRegistration()
    return render(request, "pages/customer_register.html", {'form': form})


def Logins(request):
    if request.method == "POST":
        user = request.POST['username']
        pwd = request.POST['password']
        check = models.CustomerUsers.objects.filter(username=user, password=pwd).values()
        if check:
            global currentuser, cart_bill_data, phone_verification
            temp = check[0]
            cart_bill_data = []
            currentuser = temp['user_id']
            if temp['phone_verify']:
                models.CustomerCart.objects.filter(customerusername=currentuser).delete()
                # return redirect('customers:shop')
                phone_verification = False
                return render(request, "maps/current_location.html")
            else:
                return redirect('customers:mobileverify', "new")
        else:
            messages.error(request, f"Invalid UserName and Password...! Try Again ")
            return render(request, "pages/customer_Login.html")

    return render(request, "pages/customer_Login.html")


def Home(request, home_lat, home_long):
    global lat, long
    # lat = home_lat
    # long = home_long
    print(lat, long)
    d = locationfunctions.shoploc(lat, long)
    pro_data = []
    imgs = []
    for i in d:
        a_pro = AgentProducts.objects.filter(agentsusers=i['agent_id']).values()
        if a_pro:
            print(a_pro)
            find_l = len(a_pro)
            print("yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy")
            print(find_l)
            lis = [*range(0,find_l,1)]
            find = random.choice(lis)
            print(find)
            pro_one = a_pro[find]
            nap = Napproducts.objects.filter(product_id=pro_one['product_id_id']).values()
            nap_one = nap[0]
            a_pro_one = a_pro[0]
            nap_img = Napproducts.objects.get(product_id=pro_one['product_id_id'])
            temp = {
                'name': nap_one['name'],
                'cost' : a_pro_one['cost'],
                'offer' : a_pro_one['offer'],
                'img' : nap_img
            }
            pro_data.append(temp)
            imgs.append(nap_img)

    data = [d, imgs, pro_data]
    return render(request, "pages/home.html", {"data": data})

def FirstHome(request):
    return render(request, "pages/firsthome.html")

def LogOut(request):
    global currentuser, mnumber, lat, long, shopid, cart_bill_data, phone_verification
    models.CustomerCart.objects.filter(customerusername=currentuser).delete()
    currentuser = ""
    mnumber =  ""
    # lat = ""
    # long = ""
    shopid = ""
    cart_bill_data = []
    phone_verification = False
    return redirect('customers:firstgome')


        
def FindCat():
    d = locationfunctions.shoploc(lat, long)
    temp1 = []
    temp = []
    for cname in d:
        if cname['name'] not in temp1:
            temp1.append(cname['name'])
            temp.append(cname)
    return temp

def ShopSearch(request):
    if not currentuser or  not lat or not long or  phone_verification:
        return redirect('customers:login')
    if request.method == "POST":
        pattern = request.POST['search']
        d = shopsearch.SearchFind(pattern, lat, long)
    else:
        d = []
    c = FindCat()
    data =[c,d]
    return render(request, "pages/shopsearch.html", {"data": data})

def Findshops(id):
    d = locationfunctions.shoploc(lat, long)
    shop_id = id
    if id == "fristshop":
        temp = d[0]
        shop_id = temp['agent_shop_categorie_id']
    data = []
    for sort_cat in d:
        if shop_id == sort_cat['agent_shop_categorie_id']:
            data.append(sort_cat)
    return data


def Shops(request):
    print(currentuser)
    print(phone_verification)
    if not currentuser or  phone_verification:
        return redirect('customers:login')
    d = Findshops("fristshop")
    c = FindCat()
    data =[c,d]
    return render(request, "pages/customer_shops.html", {'data':data})
    # return render(request, "pages/shopnotfound.html")
    # return render(request, "pages/customer_forgot_password.html")


def SpecificShop(request, uuid_id):
    if not currentuser or  not lat or not long or phone_verification:
        return redirect('customers:login')
    d = Findshops(uuid_id)
    c = FindCat()
    data = [c,d]
    return render(request, "pages/customer_shops.html", {'data': data})


def Orders(request):
    if not currentuser or not lat or not long or phone_verification:
        return redirect('customers:login')
    order_ass = models.CustomerOrders.objects.filter(customerusername=currentuser).order_by('oder_date').values()
    orderinfo = order_ass[::-1]
    data = []
    for oinfo in orderinfo:
        temp = {}
        t1 = oinfo
        user_info = models.CustomerUsers.objects.filter(user_id=currentuser).values()
        user_info_one = user_info[0]
        t1['name'] = user_info_one['name']

Customer/templates/layout/customer_base.html
{% load static %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'layout/customer_base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pages/footer_page.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'layout/customer_base.js' %}">
    <title>NapSack</title>
    {% block css %}
    {% endblock css %}
</head>
<body>
    <div class="base-navbar-container">
        <div class="navbar-log">
            <img src="{% static 'images/logo.png'  %}">
        </div>
        <div class="navbar-search-container">
            <input type="text" >
            {% bs_icon 'search' size='1.5em' %}
        </div>
        <div class="navbar-info">
            {% bs_icon 'truck' size='1.5em' %}
            <a href="{% url 'dealers:dearlerlogin' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Be a Dealer</p></a>
        </div>
        <div class="navbar-info">
            {% bs_icon 'person-bounding-box' size='1.5em' %}
            <a href="{% url 'agents:AgentsLogin' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Be a Agent</p></a>
        </div>
        <div class="navbar-info">
            {% bs_icon 'person-rolodex' size='1.8em' %}
            <a href="{% url 'customers:login' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Login</p></a>
        </div>
        <div class="navbar-info">
            {% bs_icon 'cart3' size='1.8em' %}
            <a href="{% url 'customers:login' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Cart</p></a>
        </div>
    </div>
    <div class="navbar-down">
        {% block navbar-down %}

        {% endblock navbar-down %}
    </div>
    <div class="base-container">
        {% block itemscontainers %}

        {% endblock itemscontainers %}
    </div>
    <div class="footer-container">
        {% include 'pages/footer_page.html' %}
    </div>

</body>
</html>

Customer/templates/layout/customer_login.html
{% load static %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'layout/customer_base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pages/footer_page.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'layout/customer_base.js' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>NapSack</title>
    {% block css %}
    {% endblock css %}
</head>
<body>
    <div class="base-navbar-container">
        <a href="{% url 'customers:shop' %}">
        <div class="navbar-log" >
            <img src="{% static 'images/logo.png'  %}">
        </div>
        </a>
        <div class="navbar-search-container">
            <form action="{% url 'customers:shopsearch' %}" method="post" >
                {% csrf_token %}
                <input type="text" placeholder="Search For Shops" name="search">
                <button type="submit" style="border: none; background-color: #3498db;">{% bs_icon 'search' size='1.5em' %}</button>
            </form>
            
        </div>
        <div class="navbar-info">
            {% bs_icon 'truck' size='1.5em' %}
            <a href="{% url 'dealers:dearlerlogin' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Be a Dealer</p></a>
        </div>
        <div class="navbar-info">
            {% bs_icon 'person-bounding-box' size='1.5em' %}
            <a href="{% url 'agents:AgentsLogin' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Be a Agent</p></a>
        </div>
        <div class="navbar-info" style="width: 120px;">
            {% bs_icon 'person-rolodex' size='1.8em' %} 
            <div class="navbar" style="margin-left: 10px;"> 
                <div class="dropdown">
                    <button class="dropbtn" >    
                    <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <br>
                    <a href="{% url 'customers:Orders' %}">orders</a>
                    <a href="{% url 'customers:customerprofile' %}">Profile</a>
                    <a href="{% url 'customers:logout' %}">Logout</a>
                    <br>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-info">
            {% bs_icon 'cart3' size='1.8em' %}
            <a href="{% url 'customers:cart' %}" style="color: inherit;text-decoration: inherit;"><p style="margin-left: 3px">Cart</p></a>
        </div>
    </div>
    <div class="navbar-down">
        {% block navbar-down %}

        {% endblock navbar-down %}
    </div>
    <div class="base-container">
        {% block itemscontainers %}

        {% endblock itemscontainers %}
    </div>
    <div class="footer-container">
        {% include 'pages/footer_page.html' %}
    </div>

</body>
</html>