Agents/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'agents'

urlpatterns = [
    path('', views.AgentsLogin, name="AgentsLogin"),
    path('agentsregister/',views.AgentsRegister, name="AgentsRegister"),
    path('agentshome/', views.AgentsHome,name="AgentsHomePage"),
    path('agentsorder/', views.Orders, name="AgentsOrders"),
    path('agentsorderdetails/<uuid:uuid_id>/', views.OrderDetails, name="Agentsorderdetails"),
    path('agentsaddproductsinfo/', views.AddProductsInfo, name="Agentsaddproductsinfo"),
    path('agentsaddproductsinfo/<uuid:uuid_id>/', views.AddProducts, name="Agentsaddproducts"),
    path('agentsproducts/', views.Products, name="Agentsproducts"),
    path('agentsproducts/<uuid:uuid_id>/', views.Productsupdate, name="Agentsproductupdate"),
    path('agentsproductsremove/<uuid:uuid_id>/', views.ProductRemove, name="Agentsproductremove"),
    path('shoplocation/<str:str_lat>/<str:str_long>/', views.ShopLoction, name="shoploc"),
    path('addcategory/<uuid:uuid_id>/', views.AddCategory, name="addcategory"),
    path('agentsorderupdate/<uuid:uuid_id>/', views.AgentsOrderUpdate, name="agentsorderupdate"),
    path('selectcategory/', views.SelectCategory, name="selectcategory"),
    



    path('example/', views.example)
]

Customer/urls.py
from django.urls import path
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'customers'

urlpatterns = [
    path('home/<str:home_lat>/<str:home_long>/', views.Home, name="home"),
    path('', views.FirstHome, name="firstgome"),
    path('addtocart/<uuid:uuid_id>/', views.AddtoCart, name="addtocart"),
    path('removecart/<uuid:uuid_id>/', views.RemoveCart, name="removecart"),
    path('cartbill/<str:quantity>/', views.CartBill, name="cartbill"),
    path('paynow/', views.PayNow, name="paynow"),
    path('login/', views.Logins, name="login"),
    path('register/', views.Registers, name="register"),
    path('orders/', views.Orders, name="Orders"),
    path('cart/', views.Cart, name = "cart"),
    path('Phoneverify/', views.Phoneverify, name="Phoneverify"),
    path('OtpVerify/', views.OtpVerify, name="Otp"),
    path('customerproducts/<uuid:uuid_id>/', views.Products, name ="products"),
    path('specificcat/<uuid:uuid_id>/', views.SpecificCategory, name="specificcat"),
    path('customerproduct/<uuid:uuid_id>/', views.Product, name ="product"),
    path('currentloc/<str:str_lat>/<str:str_long>/', views.CurrentLoc, name="curloc"),
    path('mobileverify/<str:str_info>/', views.MobileVerify, name="mobileverify"),
    path('specificshop/<uuid:uuid_id>/', views.SpecificShop, name="specificshop"),
    path('shops/', views.Shops, name="shop"),
    path('deliveryoption/', views.DeliveryOption, name="deliveryoption"),
    re_path(r'^payment/(?P<p>.*)$', views.PaymentVerifyRequest),
    path('cashondeliver/', views.CashOnDeliveryRequest, name="cashonedelivery"),
    path('logout/', views.LogOut, name="logout"),
    path('shopsearch/', views.ShopSearch, name="shopsearch"),
    path('productsearch/', views.ProductSearch, name="productsearch"),
    path('shopnotfiund/', views.ShopNotFound, name="shopnotfound"),
    path('customerprofile/', views.CustomerProfile, name="customerprofile"),
    path('customerimage/', views.UpdateProfileImage, name="customerimage"),
    path('customerforgotpassword/', views.ForgotPassword, name="forgotpassword"),
    path('customerupdatepassword/', views.UpdateForgotPassword, name="updatepassword"),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

Napsack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('agents/', include('Agents.urls'), name="agents"),
    path('', include('Customer.urls'), name="customer"),
    path('dealer/', include('Dealer.urls'), name="dealer"),
    path('payments/', include('Payments.urls'), name="payments"),
 ]
#
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# from django.conf import settings
# from django.conf.urls.i18n import i18n_patterns
# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import include, path
#
# urlpatterns = i18n_patterns(path('admin/', admin.site.urls), prefix_default_language=False) + \
#     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
#     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Customer/forms.py
from django import forms
from .models import CustomerImages, CustomerUsers

class CLogin(forms.ModelForm):
    class Meta:
        model = CustomerUsers
        fields = ('username', 'password')


class CRegistration(forms.ModelForm):
    class Meta:
        model = CustomerUsers
        exclude = ['created_on']

    def __init__(self, *args, **kwargs):
        super(CRegistration, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs \
            .update({
            'placeholder': 'Full Name',
            # 'class': 'input-calss_name'
        })
        self.fields['username'].widget.attrs \
            .update({
            'placeholder': 'Username',
        })
        self.fields['email'].widget.attrs \
            .update({
            'placeholder': 'EMail',
        })
        self.fields['password'].widget.attrs \
            .update({
            'placeholder': 'Password',
        })
        self.fields['phone_number'].widget.attrs \
            .update({
            'placeholder': 'Phone Number',
        })


class CustomerImagesForm(forms.ModelForm):
    class Meta:
        model = CustomerImages
        fields = ['image']

Customer/views.py
import email
from statistics import mode
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse
from . import shopsearch

from Customer.shopsearch import search
from . import forms
from Agents.AgentsFunctions import phone_verify, password_check
from . import models
from django.contrib import messages
import random
import requests
from django.shortcuts import redirect, reverse
from  . import locationfunctions
from Agents.models import AgentShopCategorie, AgentProducts, AgentsUsers
from NapsackAdmin.models import ShopsCategories,Products as Napproducts,ProductsCategories
from . import payments
from . import cartfunctions
import random
currentuser = ""
mnumber = ""
lat = "16.439135"
long = "80.624908"
# lat = ""
# long = ""
shopid = ""
cart_bill_data = []
sp = ""
phone_verification = True

def Phoneverify(request):
    if request.method == 'POST':
        po = request.POST['phone']
        otp = random.randint(1000, 9999)
        x = requests.request("GET", f'https://2factor.in/API/V1/df1606dc-a515-11ec-a4c2-0200cd936042/SMS/{po}/{otp}/NapSack')
        s = x.json()
        # global temp
        # temp = otp
        if s['Status'] == "Success":
            return redirect(reverse('Otp'))
        else:
            return HttpResponse("<h1>try again</h1>")

    return render(request, "forms/PhoneVerify.html")


def OtpVerify(request):
    # if request.method == 'POST':
    #     otp = request.POST['otp']
    #     if otp == str(temp):
    #         return redirect(reverse('Register'))
    #     else:
    #         return HttpResponse("<h1>wrong</h1>")
    return render(request, "forms/otpverify.html")

votp = 0
def MobileVerify(request, str_info):
    global votp
    if str_info == "new":
        cuser = models.CustomerUsers.objects.filter(user_id=currentuser).values()
    else:
        cuser = models.CustomerUsers.objects.filter(username=str_info).values()
    cuser_one = cuser[0]
    phone_number = cuser_one['phone_number']
    data = {
        'phone': phone_number,
        'info': str_info
    }
    if request.method == 'POST':
        v1 = request.POST['v1']
        v2 = request.POST['v2']
        v3 = request.POST['v3']
        v4 = request.POST['v4']
        v5 = request.POST['v5']
        otp = v1+v2+v3+v4+v5
        if otp == str(votp):
            if str_info == "new":
                models.CustomerUsers.objects.filter(user_id=currentuser).update(phone_verify=True)
                return redirect('customers:login')
            else:
                return redirect('customers:updatepassword')
        else:
            messages.error(request, f" Invalid OTP...! Try Again ")
            return render(request, 'pages/MobileVerify.html', {'data':data})
    else:
        # otp = random.randint(10000, 99999)
        otp = 11111
        # x = requests.request("GET",f'https://2factor.in/API/V1/df1606dc-a515-11ec-a4c2-0200cd936042/SMS/{phone_number}/{otp}/NapSack')
        # s = x.json()
        votp = otp
        # if s['Status'] == "Success":
        return render(request, 'pages/MobileVerify.html', {'data':data})
        # else:
        #     return HttpResponse("<h1>try again</h1>")



def Registers(request):
    if request.method == "POST":
        form = forms.CRegistration(request.POST, request.FILES)
        print(form.errors)
        pcheck = password_check(request.POST['password'])
        pnum = request.POST['phone_number']
        if pcheck == "correct":
            if phone_verify(pnum):
                print("checjjjjjjjjjjjj")
                if form.is_valid():
                    form.save()
                    cusername = form.cleaned_data['username']
                    c_user = models.CustomerUsers.objects.filter(username=cusername).values()
                    c_user_one = c_user[0]
                    customer_image_save = models.CustomerImages(user_id = c_user_one['user_id'])
                    customer_image_save.save()
                    global currentuser
                    currentuser = c_user_one['user_id']
                    messages.success(request, f"New account created:")
                    return redirect('customers:mobileverify', "new")
                    # return redirect('customers:login')
                else:
                    # form = forms.ALogin()
                    messages.error(request, f" UserName already exit...! Try Again  ")
                    # AgentsMessages.my_view(request,f" UserName already exit...! Try Again  ")
                    return render(request, "pages/customer_register.html", {'form': form})
            else:
                messages.warning(request, f" Invalid Phone Number..! please include country code eg:+91  ")
                return render(request, "pages/customer_register.html", {'form': form})

        else:
            # form = forms.ALogin()
            messages.info(request, f" {pcheck} ")
            return render(request, "pages/customer_register.html", {'form': form})
    else:
        form = forms.CRegistration()
    return render(request, "pages/customer_register.html", {'form': form})


def Logins(request):
    if request.method == "POST":
        user = request.POST['username']
        pwd = request.POST['password']
        check = models.CustomerUsers.objects.filter(username=user, password=pwd).values()
        if check:
            global currentuser, cart_bill_data, phone_verification
            temp = check[0]
            cart_bill_data = []
            currentuser = temp['user_id']
            if temp['phone_verify']:
                models.CustomerCart.objects.filter(customerusername=currentuser).delete()
                # return redirect('customers:shop')
                phone_verification = False
                return render(request, "maps/current_location.html")
            else:
                return redirect('customers:mobileverify', "new")
        else:
            messages.error(request, f"Invalid UserName and Password...! Try Again ")
            return render(request, "pages/customer_Login.html")

    return render(request, "pages/customer_Login.html")


def Home(request, home_lat, home_long):
    global lat, long
    # lat = home_lat
    # long = home_long
    print(lat, long)
    d = locationfunctions.shoploc(lat, long)
    pro_data = []
    imgs = []
    for i in d:
        a_pro = AgentProducts.objects.filter(agentsusers=i['agent_id']).values()
        if a_pro:
            print(a_pro)
            find_l = len(a_pro)
            print("yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy")
            print(find_l)
            lis = [*range(0,find_l,1)]
            find = random.choice(lis)
            print(find)
            pro_one = a_pro[find]
            nap = Napproducts.objects.filter(product_id=pro_one['product_id_id']).values()
            nap_one = nap[0]
            a_pro_one = a_pro[0]
            nap_img = Napproducts.objects.get(product_id=pro_one['product_id_id'])
            temp = {
                'name': nap_one['name'],
                'cost' : a_pro_one['cost'],
                'offer' : a_pro_one['offer'],
                'img' : nap_img
            }
            pro_data.append(temp)
            imgs.append(nap_img)

    data = [d, imgs, pro_data]
    return render(request, "pages/home.html", {"data": data})

def FirstHome(request):
    return render(request, "pages/firsthome.html")

def LogOut(request):
    global currentuser, mnumber, lat, long, shopid, cart_bill_data, phone_verification
    models.CustomerCart.objects.filter(customerusername=currentuser).delete()
    currentuser = ""
    mnumber =  ""
    # lat = ""
    # long = ""
    shopid = ""
    cart_bill_data = []
    phone_verification = False
    return redirect('customers:firstgome')


        
def FindCat():
    d = locationfunctions.shoploc(lat, long)
    temp1 = []
    temp = []
    for cname in d:
        if cname['name'] not in temp1:
            temp1.append(cname['name'])
            temp.append(cname)
    return temp

def ShopSearch(request):
    if not currentuser or  not lat or not long or  phone_verification:
        return redirect('customers:login')
    if request.method == "POST":
        pattern = request.POST['search']
        d = shopsearch.SearchFind(pattern, lat, long)
    else:
        d = []
    c = FindCat()
    data =[c,d]
    return render(request, "pages/shopsearch.html", {"data": data})

def Findshops(id):
    d = locationfunctions.shoploc(lat, long)
    shop_id = id
    if id == "fristshop":
        temp = d[0]
        shop_id = temp['agent_shop_categorie_id']
    data = []
    for sort_cat in d:
        if shop_id == sort_cat['agent_shop_categorie_id']:
            data.append(sort_cat)
    return data


def Shops(request):
    print(currentuser)
    print(phone_verification)
    if not currentuser or  phone_verification:
        return redirect('customers:login')
    d = Findshops("fristshop")
    c = FindCat()
    data =[c,d]
    return render(request, "pages/customer_shops.html", {'data':data})
    # return render(request, "pages/shopnotfound.html")
    # return render(request, "pages/customer_forgot_password.html")


def SpecificShop(request, uuid_id):
    if not currentuser or  not lat or not long or phone_verification:
        return redirect('customers:login')
    d = Findshops(uuid_id)
    c = FindCat()
    data = [c,d]
    return render(request, "pages/customer_shops.html", {'data': data})


def Orders(request):
    if not currentuser or not lat or not long or phone_verification:
        return redirect('customers:login')
    order_ass = models.CustomerOrders.objects.filter(customerusername=currentuser).order_by('oder_date').values()
    orderinfo = order_ass[::-1]
    data = []
    for oinfo in orderinfo:
        temp = {}
        t1 = oinfo
        user_info = models.CustomerUsers.objects.filter(user_id=currentuser).values()
        user_info_one = user_info[0]
        t1['name'] = user_info_one['name']

Customer/templates/pages/customer_cart.html
{% extends 'layout/customer_login.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/customer_cart.css' %}"
      xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="sweetalert2.min.css">
{% endblock css %}
{% block itemscontainers %}
<h1 class="count" style="display: none; font-size: 0px">{{ data|length }}</h1>
<div class="cart-container">
    {% if data %}
        <div class="cart-lists">
            {% for i in data %}
            <div class="cart-each-product">
                <div class="cart-each-img">
                    <img src="{{ i.img.image.url }}" >
                </div>
                <div class="cart-each-info">
                    <a href="{% url 'customers:product' i.product_id %}"><h4>{{ i.product_name }}</h4></a>
                    <br>
                    <h3 style="margin-bottom: 5px" >Cost: ₹<span id="cost{{ i.class_name }}">{{ i.cost }}</span><strike>₹<span id="actualcost{{ i.class_name }}">{{ i.Actual_cost }}</span></strike> {{ i.offer }}% Off</h3>
                    <label for="qty" style="font-size: 20px">Qty:</label>
                    <select id="{{ i.class_name }}" name="qty" style="width: 40px;height: 20px" onchange="bill()">
                        {% for j in i.qty %}
                        <option value={{ j }}>{{ j }}</option>
                        {% endfor %}
                    </select>

                    <br>
                 <button onclick="removeconformation()" id="Url"  data-url="{% url 'customers:removecart'  i.product_id  %}">Remove</button>
                </div>
            </div>
            {% endfor %}

        </div>
    
        <div class="cart-info">
            <div class="cart-info-bill-details" >
                <br>
                <h1 style="text-align: center;">PRICE DETAILS</h1>
                <br>
                <table>
                    <tr>
                        <td>Price ({{ data|length }}items)</td>
                        <td id="price"></td>
                    </tr>
                    <tr>
                        <td>Discount</td>
                        <td id="discount"></td>
                    </tr>
                    <tr>
                        <td>Delivery Charges</td>
                        <td id="Charges">FREE</td>
                    </tr>
                    <tr>
                        <td><h2>Total Amount</h2></td>
                        <td><h2 id="total"></h2></td>
                    </tr>
                </table>
            </div>
            <div class="cart-info-placeorder" style="background-color: white;">
                <h3 id="billinfo" ></h3>
            </div>
            <div class="cart-info-placeorder" style="border-radius: 20px;cursor: pointer">
                <h1 onclick="getqty()">Place Order</h1>
            </div>
        </div>
        {% else %}
        <div>
            <h1>No Items in Cart</h1>
            <br>
            <h1 style="color: orange;">Get Products From Nearest Shop With in 2-3 hours</h1> <br>
        <h1 style="color: orange;"><a href="{% url 'customers:shop' %}"> Click Her </a> To Find The Shops</h1>
        </div>
        {% endif %}
</div>
<script src="sweetalert2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var count = document.querySelector(".count").textContent;
        var qtycount = "qty"
        function getqty(){
            for (let i = 1; i <= count; i++) {
               temp = "c"+i
               console.log(temp)
               var x = ((document.getElementById(temp)||{}).value)||"";
               qtycount = qtycount + x
            }
            console.log(qtycount)
            // alert(qtycount)
            // window.location.href = "http://127.0.0.1:8000/customer/" + lat + "/" + long;
            window.location.href = "http://127.0.0.1:8000/cartbill/" + qtycount;
            qtycount = "qty"
        }
        totalcost  = 0
        toatlactualcost = 0
         function find(){
            for (let i = 1; i <= count; i++) {
                t = "costc"+i
                var cost = document.getElementById(t).innerHTML
                t = "actualcostc"+i
                var actualcost = document.getElementById(t).innerHTML
                temp = "c"+i
                var x = ((document.getElementById(temp)||{}).value)||"";
                qty = parseInt(x)
                totalcost = totalcost + (parseInt(cost) * qty);
                toatlactualcost = toatlactualcost + (parseInt(actualcost) * qty);
                 console.log(totalcost)
                  console.log(toatlactualcost)
                console.log(typeof qty)
            }
        }
        function bill(){
            find()
            if (totalcost <= 500 &  totalcost > 0){
                totalcost =  totalcost + 40
                document.getElementById("Charges").innerHTML = "+" + 40
                document.getElementById("billinfo").innerHTML = "You will save " + "₹" + (toatlactualcost - totalcost) +" on this order";
            }
            else {
                document.getElementById("billinfo").innerHTML = "You will save " + "₹" + (toatlactualcost - totalcost) +" on this order";
            }
            document.getElementById("price").innerHTML = "₹" + " " + toatlactualcost;
            document.getElementById("discount").innerHTML = "-" + " " + (toatlactualcost - totalcost);
            document.getElementById("total").innerHTML = "₹" + " " + totalcost

            totalcost  = 0
            toatlactualcost = 0
        }
        function removeconformation(){
            Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this Product!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, Remove from cart!'
            }).then((result) => {
            if (result.isConfirmed) {
                var url = $("#Url").attr("data-url");
                document.location.href = url
            }
            })
        };



        bill();
</script>

{% endblock itemscontainers %}

Customer/templates/pages/customer_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        integrity="sha256-UhQQ4fxEeABh4JrcmAJ1+16id/1dnlOEVCFOxDef9Lw=" crossorigin="anonymous" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        integrity="sha256-kksNxjDRxd/5+jGurZUJd1sdR2v+ClrCl3svESBaJqw=" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/23412c6a8d.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/customer_login.css' %}">

</head>

<body>

    <div class="container">
        <div class="panel">
            <div class="row">
                <div class="col liquid"  style="background-image: url('{% static 'images/pages/Wave.png' %}')">
                    <h4><img src="{% static 'images/logo.png' %}" style="height: 100px;width: 200px;"></h4>
                    <div class="owl-carousel owl-theme">
                        <img src="{% static 'images/pages/c2.jpg' %}" alt="" class="login_img">
                        <img src="{% static 'images/pages/c3.png' %}" alt="" class="login_img">
                        <img src="{% static 'images/pages/c1.jpg' %}" alt="" class="login_img">

                    </div>
                    <div class="follow">
                        Follow us <i class="fab fa-facebook-f"></i>
                        <i class="fab fa-twitter"></i>
                        <i class="fab fa-instagram"></i>
                        <i class="fab fa-linkedin"></i>
                    </div>
                </div>
                <div class="col login">
                    <div class="containerform">
                        <form method="post">
                            {% csrf_token %}
                            <p> Login To NapSack</p>
                            <i class="fas fa-user" ></i>
                            <input type="text" placeholder="Username" name="username"><br>
                            <i class="fas fa-user-lock"></i>
                            <input type="password" placeholder="Password" name="password"><br>
                            <br>
                            <input type="submit" style="background: rgb(168, 247, 247);">
                            {% if messages %}
                              {% for message in messages %}
                                 {% if message.tags == 'error' %}
                                  <div style="height: 40px;width: 320px;color: darkred">
                                    <strong>{{message}}</strong>
                                  </div>
                                 {% endif %}
                              {% endfor %}
                            {% endif %}
                            <br>
                            <a href="{% url 'customers:forgotpassword' %}">Forgot Password?</a>

                            <p style="margin-bottom: 0px;">or</p>
                            <button type="button" class="btn"><a href="{% url 'customers:register' %}">
                                Sign up </a></button>
                        </form>

                        <div class="drops">
                            <div class="drop drop-1"></div>
                            <div class="drop drop-2"></div>
                            <div class="drop drop-3"></div>
                            <div class="drop drop-4"></div>
                            <div class="drop drop-5"></div>
                            <div class="drop drop-6"></div>
                        </div>
                    </div>
                    <button type="button" class="btn btn-signup"><a href="{% url 'agents:AgentsLogin' %}">
                        NapSack Agent</a></button>

                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
        integrity="sha256-pTxD+DSzIwmwhOqTFN+DB+nHjO4iAsbgfyFq5K5bcE0=" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {

            $('.owl-carousel').owlCarousel({
                loop: true,
                autoplay: true,
                autoplayTimeout: 2000,
                autoplayHoverPause: true,
                items: 1
            });
        });
    </script>
</body>

</html>

Customer/templates/pages/customer_profile.html
{% extends 'layout/customer_login.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/customer_profile.css' %}">
{% endblock css %}
{% block itemscontainers %}
<div class="profile-container">
    <div class="profile-card">
        <div class="profile-img-container">
            {% for form in data %}
            {% if forloop.last %}
            <img src="{{ form.img.image.url }}" alt="profile" class="profile-img">
            {% endif %}
            {% endfor %}
            {% for form in data %}
            {% if forloop.first %}
            <form method="post" action="{% url 'customers:customerimage' %}" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form }}
                <br>
                <button type="submit">Update</button>
            </form>
            {% endif %}
            {% endfor %}
        </div>
        <div class="profile-info-container">
            <img src="{% static 'images/napsacklogo.png' %}">
            <br>
            <br>
            <br>
            {% for i in data %}
            {% if forloop.last %}
            <form method="post" action="{% url 'customers:customerprofile' %}">
                {% csrf_token %}
                <div class="each-input-container">
                    <input type="text" name="username" placeholder="Username" value="{{ i.username }}">
                    <button type="submit">Update</button>
                </div>
                <div class="each-input-container">
                <input type="text" name="name" placeholder="Name" value="{{ i.name }}">
                <button type="submit">Update</button>
                </div>
                <div class="each-input-container">
                <input type="text" name="email" placeholder="Email" value="{{ i.email }}">
                <button type="submit">Update</button>
                </div>
                <div class="each-input-container">
                <input type="text" name="phone" placeholder="Phone" value="{{ i.phone_number }}">
                <button type="submit">Update</button>
                </div>
                <div class="each-input-container">
                <input type="text" name="password" placeholder="Password" value="{{ i.password }}">
                <button type="submit">Update</button>
                </div>
            </form>
            {% endif %}
            {% endfor %}
            {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                <div style="height: 40px;width: 320px;color: darkred; text-align: center;">
                <strong>{{message}}</strong>
                </div>
                <br>
                    <br>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
            <div style="height: 40px;width: 320px;color: rgb(251, 130, 31); text-align: center;">
            <strong>{{message}}</strong>
            </div>
            <br>
                    <br>
            {% endif %}
        {% endfor %}
        {% endif %}
        </div>
        
    </div>
    
</div>


{% endblock itemscontainers %}